drop table if exists mp CASCADE;
create table mp
(
    id bigint generated by default as identity,
    HG_NM varchar(255),
    HJ_NM varchar(255),
    ENG_NM varchar(255),
    BTH_GBN_NM varchar(255),
    BTH_DATE varchar(255),
    JOB_RES_NM varchar(255),
    POLY_NM varchar(255),
    ORIG_NM varchar(255),
    ELECT_GBN_NM varchar(255),
    CMIT_NM varchar(255),
    CMITS varchar(255),
    REELE_GBN_NM varchar(255),
    UNITS varchar(255),
    SEX_GBN_NM varchar(255),
    TEL_NO varchar(255),
    E_MAIL varchar(255),
    HOMEPAGE varchar(255),
    STAFF varchar(255),
    SECRETARY varchar(255),
    SECRETARY2 varchar(255),
    mona varchar(255),
    MEM_TITLE varchar(1000),
    ASSEM_ADDR varchar(255),
    primary key (id)
);